version: "3.9"
services:
  frontend:
    image: jungnoh-vote-app:latest
    environment:
      - APP_PORT=3000
    expose:
      - "3000"
    restart: always
  backend:
    image: jungnoh-vote-server:latest
    environment:
      - MONGO_HOST=mongodb://db:27017/vote
      - SESSION_SECRET=foo
      - SERVER_PORT=8080
    expose:
      - "8080"
    restart: always
  proxy:
    image: jungnoh-vote-proxy:latest
    restart: always
    ports:
      - "80:80"
  db:
    image: mongo:4.4
    expose:
      - "27017"
